# Generated by Django 4.1.3 on 2022-12-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('team', models.CharField(choices=[('Recipeasy', 'Recipeasy'), ('Forgetmenot', 'Forgetmenot'), ('Prefolio', 'Prefolio'), ('Diametes', 'Diametes'), ('Teample', 'Teample')], max_length=20)),
                ('demoday', models.BooleanField(default=False)),
                ('part', models.BooleanField(default=False)),
            ],
        ),
    ]
