<<<<<<< HEAD
# Generated by Django 4.1.3 on 2022-12-03 12:25
=======
# Generated by Django 4.1.3 on 2022-12-07 06:14
>>>>>>> 202d2f30d0ad5198c1aa7633bc846d76d9ec1046

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

<<<<<<< HEAD
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "position",
                    models.CharField(
                        choices=[("FE", "FRONTEND"), ("BE", "BACKEND")], max_length=2
                    ),
                ),
                ("vote_count", models.IntegerField(default=0)),
=======
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('position', models.CharField(choices=[('FE', 'FRONTEND'), ('BE', 'BACKEND')], max_length=2)),
                ('vote_count', models.IntegerField(default=0)),
>>>>>>> 202d2f30d0ad5198c1aa7633bc846d76d9ec1046
            ],
        ),
    ]
