# Generated by Django 4.1.3 on 2022-12-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "position",
                    models.CharField(
                        choices=[("FE", "FRONTEND"), ("BE", "BACKEND")], max_length=2
                    ),
                ),
                ("vote_count", models.IntegerField(default=0)),
            ],
        ),
    ]
