# Generated by Django 4.1.3 on 2022-12-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partleads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
