# Generated by Django 4.1.3 on 2022-12-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partleads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="position",
            field=models.CharField(
                choices=[
                    ("FE", "FRONTEND"),
                    ("BE", "BACKEND"),
                    ("DE", "DESIGN"),
                    ("PM", "PM"),
                ],
                max_length=2,
            ),
        ),
    ]
