# Generated by Django 4.1.3 on 2022-12-20 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partleads", "0002_alter_candidate_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidate", old_name="id", new_name="candidate_id",
        ),
    ]
