# Generated by Django 4.1.3 on 2022-12-20 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partleads", "0003_rename_id_candidate_candidate_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidate", old_name="candidate_id", new_name="id",
        ),
    ]
