# Generated by Django 4.1.3 on 2022-12-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partleads", "0004_rename_candidate_id_candidate_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="position",
            field=models.CharField(
                choices=[("Frontend", "Frontend"), ("Backend", "Backend")], max_length=8
            ),
        ),
    ]
