# Generated by Django 4.1.3 on 2022-12-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeasy', models.IntegerField(default=0)),
                ('forgetmenot', models.IntegerField(default=0)),
                ('prefolio', models.IntegerField(default=0)),
                ('diametes', models.IntegerField(default=0)),
                ('teample', models.IntegerField(default=0)),
            ],
        ),
    ]
