# Generated by Django 4.1.3 on 2022-12-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_name",
                    models.CharField(
                        choices=[
                            ("RECIPEASY", "RECIPEASY"),
                            ("TEAMPLE", "TEAMPLE"),
                            ("FORGET_ME_NOT", "FORGET_ME_NOT"),
                            ("PREFOLIO", "PREFOLIO"),
                            ("DIAMETES", "DIAMETES"),
                        ],
                        max_length=20,
                    ),
                ),
                ("vote_count", models.IntegerField(default=0)),
            ],
        ),
    ]
