# Generated by Django 4.1.3 on 2022-12-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoday", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="team_name",
            field=models.CharField(
                choices=[
                    ("Recipeasy", "Recipeasy"),
                    ("Forgetmenot", "Forgetmenot"),
                    ("Prefolio", "Prefolio"),
                    ("Diametes", "Diametes"),
                    ("Teample", "Teample"),
                ],
                max_length=20,
            ),
        ),
    ]
