# Generated by Django 4.1.3 on 2022-12-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoday", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
