# Generated by Django 4.1.3 on 2022-12-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoday", "0002_alter_team_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
